### PR TITLE
RFC: Internalize step creation to significantly reduce API surface

### PR DESCRIPTION
**Pull request by adam-rhebo**
This will also improve diagnostics through less macro-based open coding, but it will also imply a change of the actual interface even though no change to the effective interface if one sticks to the macros.

### CODE REVIEW

**Comment by bbqsrc** [comment]
I would ask that you don't bump the version in a commit and instead do it in a separate commit.

I will bump the version on release based on what has happened since the last release based on semver rules, so you need not worry about that.

Do open an issue if you want me to do a release and I haven't done one yet though! :smile:

**Comment by adam-rhebo** [comment]
> I would ask that you don't bump the version in a commit and instead do it in a separate commit.

Agreed. Will refrain from touching the field outside of the actual release process.

> Do open an issue if you want me to do a release and I haven't done one yet though! smile

Since we are currently prototyping ourselves for now, we'll probably start using a `{ git = ... }` dependency pointing here. But I'll be happy to take up the offer when we actually start merging things. Thanks!

**Comment by adam-rhebo** [comment]
I also just noticed while reviewing this that my earlier PR #15  had a bug insofar https://github.com/bbqsrc/cucumber-rust/blob/9bfb2f502c1c9b20a2d42f7671d1dc8c0a4453bc/src/lib.rs#L625 is missing `.skip(1)`. Sorry for that.

**Comment by bbqsrc** [comment]
We tend to use git master at the moment as well, so you can ensure it is going to be "vaguely stable" for now as well. Crazy stuff happens on `develop` or feature branches as one might expect. :smile:

**Pull request merged**
