### PR TITLE
Support Examples section

### PR DESCRIPTION
**Pull request by mraof**

### CODE REVIEW

**Comment by darval** [comment]
Just trying to learn cucumber and rust and I had thought I had written a valid scenario outline, which didn't appear to work.  This looks like the fix I need.

**Comment by bbqsrc** [comment]
@darval published as 0.6.2, let me know if it solves your issue.

**Comment by darval** [comment]
Ok, will check it out once it gets onto crates.io, etc.. :) . Thanks 👍

**Comment by bbqsrc** [comment]
@darval it should be there already 😄

**Comment by bbqsrc** [comment]
@darval open a new bug instead if you have further issues. :)

**Comment by darval** [comment]
ok.  Since I am new to this, I am never sure whether the bug is in your code, my code or my understanding - last two more likely. :)

**Comment by darval** [comment]
Just to close this out, it is now working how I expected. :) . Thanks again to both of you.

**Pull request merged**
