### PR TITLE
Added basic support for examples

### PR DESCRIPTION
**Pull request by stefanpieck**
PR related to #64

### CODE REVIEW

**Comment by bbqsrc** [comment]
Can you rebase and squash all your commits into the `Added a simple implementation for examples` one? Seems the mut fix is already committed and the short comment is just a fixup.

If you need help with that, just ping me.

**Comment by stefanpieck** [comment]
> Can you rebase and squash all your commits into the `Added a simple implementation for examples` one? Seems the mut fix is already committed and the short comment is just a fixup.
> 
> If you need help with that, just ping me.

Ok, I think I need some assistance for that. 
I have never done that before.

**Comment by bbqsrc** [comment]
No problem.

First, check that the `main` branch is up-to-date locally first with a pull. If you cloned the repo before I renamed `master` to `main`, `git pull --all` should grab main.

Then, to do an interactive rebase, after checking out to your feature branch, run `git rebase -i main`. This will rebase your feature branch against main. It should pop up an editor showing your three commits.

Change it so that only the top commit says pick, and change the others to say `squash` or `s`. Save.

Once you've done that you'll get another editor, this time with all the previous commit messages it's going to merge. Delete everything you don't want to keep (which is all of it except for "Added a simple implementation for examples". Save.

You should now have just one commit on that branch compared with main. 😄

**Comment by bbqsrc** [comment]
Ah, no, you have your own fork that is a few commits behind. To fix this is a bit more than I can explain in comments, I'll rebase it myself this evening and merge it for you. :smile:

**Comment by stefanpieck** [comment]
Thank you 😄

**Comment by bbqsrc** [comment]
Thanks for the contribution. I will make some modifications to this, and report on them in #64.

**Pull request merged**
