### PR TITLE
Optional step timeout, optional control over stdout/stderr capture

### PR DESCRIPTION
**Pull request by ZackPierce**
Adds configuration options for a few aspects of test execution:
* How long steps are allowed to execute
* Whether to capture stdout/stderr during step execution
   * Testing this capability required the creation of a tiny standalone binary that could be invoked and its output analyzed.

Added documentation on the `Cucumber` builder methods while I was in there.

### CODE REVIEW

**Comment by bbqsrc** [comment]
Hey, big contribution, looks pretty neat!

I've given it a read through, and will give it another read through tomorrow. Right now I only see one thing that I have a qualm with, and that's the addition of a TimedOut item separate to Failure. I would consider a timeout a _type_ of failure. Would it be possible for you to modify this PR to create a `FailureKind` enum, and make the failure arm of the relevant enums take a `Failure(FailureKind)`?

I'll give it a proper review tomorrow. Thanks again!

**Comment by ZackPierce** [comment]
Sure, I can do that.

**Comment by bbqsrc** [comment]
Ended up having less time today than I thought I'd have :(

Will give a proper review in the morning. Thanks for adding the changes I requested. :)

**Comment by bbqsrc** [comment]
This is super cool. Only change I've made was to move the capture-runner into a tests/fixtures directory. :) Thanks again!

**Pull request merged**
