### PR TITLE
Remove dependence on unstable features

### PR DESCRIPTION
**Pull request by lux01**
# Overview

Currently `cucumber-rust` relies on two unstable Rust features: `set_stdio` and `fnbox`. If this PR is accepted then cucumber-rust will be usable on stable Rust instead of nightly.
 
## `set_stdio`

This is used to capture and suppress world construction and step execution. During world construction the output is suppressed and any panic is effectively re-thrown however it actually panics with the combined contents of stdout and stderr. During step execution the is examined if a panic is caught to re-print the panic information and provide prettier panic information.

This PR removes the stdout/stderr suppression entirely. No special panic handling is done during world construction as this panic was already rethrown. During step execution the `PanicInfo` payload is down-casted to a `String` at the same time as building the location information in the panic handler.

Disabling suppression of stdout/stderr could be contentious however this is the same behaviour as the Java cucumber library.

## `fnbox`

This is used during the main function to pass in the `before` function as an optional boxed closure. This is currently defaulted to `None` if there is no `before` function defined. Instead now the default `before` argument is an empty closure and main evaluates the provided closure unconditionally.

### CODE REVIEW

**Comment by lux01** [comment]
Thanks for the feedback. I'll work on rebasing this PR to the develop branch and get a feature flag in place to toggle capturing stdout/stderr or not. Since you've already started work on the clap stuff then it shouldn't be too hard to add in a `--no-capture` flag to mimic the standard testing framework for the best of both worlds on nightly :)

**Comment by bbqsrc** [comment]
Ping me when you're done here and I'll merge; looking super good so far!

**Comment by lux01** [comment]
How am I this bad at git rebase/merges!

**Comment by lux01** [comment]
I think it's done.

Now we have a default feature called `nightly` which controls whether to use `set_stdio` or not, and a command line flag `--nocapture` which disables suppression (if running with `nightly`).

The io redirect is offloaded into the new `PanicTrap` struct and hidden behind a `#[cfg(...)]` gate to get it to compile on stable rust. Additionally I've expanded the output printer for the failure case to show the panic payload string and captured output separately.

**Comment by lux01** [comment]
Note that I've put set the `nightly` feature by default so stable is still an opt-in process.

**Comment by bbqsrc** [comment]
Manually merged to fix the commit history. 👍

**Comment by bbqsrc** [comment]
In order to fix this, I did `git rebase -i develop`, removed the top line entirely because it was an old and incorrect reference, and it simply worked. Then merged the errors into previous commits. :smile:

**Pull request closed without merging**
